curl -X POST http://localhost:5000/create_person \
-H "Content-Type: application/json" \
-d '{
"first_name": "simon",
"last_name": "simens",
"email": "simon.simens@gmail.com",
"password": "dasPassword",
"birthday": "07.11.2001"
}'