curl -X POST http://localhost:5000/create_person \
-H "Content-Type: application/json" \
-d '{
"first_name": "adrian",
"last_name": "cola",
"email": "adrian.cold@gmail.com",
"password": "187",
"birthday": "13.04.1997"
}'