curl -X POST http://localhost:5000/create_material \
-H "Content-Type: application/json" \
-d '{
"material_name": "testmaterial",
"course_name": "testkurs",
"pdf_name": "https://discord.com/material/test.pdf",
}'